app:
  name: "server-name"
  mode: "dev"
  port: 40001
  version: "v0.0.1"
log:
  level: "info"
  filename: "log/gin_server.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "myserver"
  password: "5mbCoLSCHznU0y7C"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 6
  pool_size: 100
